### ISSUE TITLE
Is it possible to run the Fleetversion from Testserver (Sisi/TD)?

### ISSUE THREAD

**Issue by Vesuvionscripts** [ArtificialQualia/PELD-Server#24]
Due the SSO not working for the Testserver would it be possible to share some client information without SSO from Fleet on the Testserver?

**Comment by ArtificialQualia** [comment]
Sadly this wouldn't be able to function correctly as fleet mode does more than just use SSO, it utilizes a number of ESI endpoints to maintain fleet information, verify characters, etc.  Since those don't exist on Sisi, fleet mode can not work there.

In either case, the main peld-fleet site has been down for some time and will probably remain down for the foreseeable future.  The site would need some changes to catch up to the latest changes in the ESI API and frankly fleet mode got so little use I'm not convinced it is worth maintaining and paying for hosting.

Feel free to reopen this ticket if you have follow up questions.

**Comment by Vesuvionscripts** [comment]
Thank you very much for the reply.

Since you really cleared out my question regarding offical CCP Part.

To make this kind of work: 
If i would just need basic information from the client site from my fleet like:

Player Name
Damage in comming
Repair receieved
Damage outgoing

(This is already done by the client without the Server)
So theoretical the client send this information (under Fleet Mode) to the Server which than get send back to the FC.
(I see these functions already in the client, Top 3 Logi out graps for example)

For all this above do we need the SSO Part?

**Comment by ArtificialQualia** [comment]
In a technical sense, you do not need SSO for sending or receiving that kind of information.  As you point out, the client has all the relevant information that is needed to make those graphs or be displayed in the fleet webapp.

The problem is: without SSO you can't verify any information being sent to the server/FC from the clients.

With no SSO/ESI api any player could say they are any character they want.  They could say they are a part of any fleet they want.  They could say they are FC of every fleet!

So that is the problem with not using SSO.  There is no way to tell who is actually in what fleets and when.
